// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa2eaoTLA4Qerzs28SK6huVHGrML1LTeU',
    authDomain: 'quavoapp.firebaseapp.com',
    projectId: 'quavoapp',
    storageBucket: 'quavoapp.firebasestorage.app',
    messagingSenderId: '984396398604',
    appId: '1:984396398604:web:37321f2c4bd34eda9e2e29',
    measurementId: 'G-BGVK9JV58E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnn5MWfQOHMz1JBvqH7oBJDLr8my9K8aE',
    appId: '1:654974191226:android:2eab68eb9a90f912d09dc3',
    messagingSenderId: '654974191226',
    projectId: 'spotifyclone-bacc2',
    storageBucket: 'spotifyclone-bacc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoF5x2j26L8ubeDyy6UUAvI4c0hc-YhHY',
    appId: '1:654974191226:ios:8cbbdf7c56abc0f6d09dc3',
    messagingSenderId: '654974191226',
    projectId: 'spotifyclone-bacc2',
    storageBucket: 'spotifyclone-bacc2.appspot.com',
    iosBundleId: 'com.example.spotify',
  );
}
